import re

PUNCTUATION_TO_EXCLUDE = [
    "|",
    "[",
    "]",
    "(",
    ")",
    "@",
    "#",
    "$",
    "&",
    "*",
    "+",
    "{",
    "}",
    "/",
    "=",
    "®",
    ">",
    "<",
    "≤",
    "–",
    "©",
]

NUMBERS = [str(i) for i in range(10)]

SENTENCE_END_CHARS = [".", "!", "?", '"', "'"]

EMOJIS = re.compile(r"[\u263a-\U0001f645]")

REPEATED_WORDS = re.compile(r"\b(\w+)\b\s+(\1)\b")

HOURS = re.compile(r"[0-2]?[0-9](:|\.)[0-5][0-9](?![0-9])")

# words that should not end a sentence
INCORRECT_SENTENCE_END_WORDS = [
    "els",
    "el",
    "la",
    "les",
    "a",
    "en",
    "de",
    "que",
    "què",
    "mitjançant",
    "del",
    "dels",
    "al",
    "als",
    "es",
    "per",
    "i",
    "amb",
    "hem",
    "ha",
    "he",
    "has",
    "heu",
    "qual",
    "han",
    "són",
    "com",
]

REPLACEMENT_WORDS = {
    "’": "'",
    "%": "per cent",
    "€": "euros",
    "sr.": "senyor",
    "dr.": "doctor",
    "sra.": "senyora",
    "dra.": "doctora",
    "st.": "Sant",
    "sta.": "Santa",
    "num.": "número ",
    "núm ": "número ",
    "núm.": "número",
    "vol.": "Volum ",
    "km.": "quilòmetres",
    "c.": " carrer",  # càrrec
    "c/": "carrer",
    "pl.": "plaça ",
    "Pl.": "Plaça ",
    "pag.": "pàgina",
    "pàg.": "pàgina",
    "p.": " pàgina",
    "ed.": "editorial",
    "h.": "hores",
    "av.": "avinguda",
    "hable.": "Honorable",
    "hble.": "honorable",
    "etc.": "etcètera",
    "pral.": "principal",
    "jr.": "júnior",
    "ptes.": " pessetes",  # aptes
    "covid-19": "Covid dinou",
    "ha.": "hectàrees",
    "veg.": "vegeu",
    "sr": "senyor",
    "dr": "doctor",
    "sra": "senyora",
    "dra": "doctora",
    "st": "Sant",
    "sta": "Santa",
    "num ": "número ",
    "núm": "número ",
    "km": "quilòmetres",
    "kv": "quilovolts",
    "kw": "quilowatts",
    "pag": "pàgina",
    "pàg": "pàgina",
    "av": "avinguda",
    "hable": "Honorable",
    "hble": "honorable",
    "ptes": "pessetes",
    "1r": "primer",
    "1a": "primera",
    "2n": "segon",
    "2a": "segona",
    "3r": "tercera",
    "4t": "quart",
    "4a": "quarta",
    "5è": "cinquè",
    "5ena": "cinquena",
    "iban": "Iban",
    "ibex": "Ibex",
    "eeuu": "Estats Units",
    "eua": "Estats Units",
    "eu": "Unió Europea",
    "ue": "Unió Europea",
    "nie": "Nie",
    "erc": "Esquerra Republicana de Catalunya",
    "ciu": "Convergiència i Unió",
    "psoe": "Partit Socialista Espanyol",
    "pp": "Partit Popular",
    "cup": "Cup",
    "psc": "Partit Socialista de Catalunya",
    "ccoo": "Comissions Obreres",
    "ampa": "associació de mares i pares d'alumnes",
    "ampas": "associacions de mares i pares d'alumnes",
    "ampes": "associacions de mares i pares d'alumnes",
    "afas": "associacions de famílies d'alumnes",
    "afes": "associacions de famílies d'alumnes",
    "afa": "associació de famílies d'alumnes",
    "tc": "Tribunal Constitucional",
    "tsjc": "Tribunal Superior de Justícia de Catalunya",
    "pimes": "Pime",
    "pime": "Pime",
    "led": "led",
    "unesco": "Unesco",
    "unicef": "Unicef",
    "sepa": "Sepa",
    "erto": "Erto",
    "dni": "document nacional d'identitat",
    "termcat": "Termcat",
}

QUOTATION_MARKS = ["‘", "’", "“", '"', "”", "«", "»"]
